name: Setup Hosting.de
description: Helpful action to build push-to-deploy actions with Hosting.de
author: Richard Henkenjohann

inputs:
  auth-token:
    description: The auth token from your Hosting.de account.
    required: true
  app:
    description: The key of the current application in the yaml manifest.
    default: app
  project-prefix:
    description:
      A unique name for webspaces that are related to the build. Example
      `my-app`. Must be unique under all projects exist under the same account.
    required: true
  ssh-public-key:
    description:
      The SSH public key that matches the private key configured for deploying.
    required: true

outputs:
  ssh-user:
    description: Username for ssh connect.
  ssh-host:
    description: Hostname for ssh connect
  ssh-port:
    description: Port for ssh connect.
  http-user:
    description: User that runs the php process (for Deployer writable action).
  deploy-path:
    description: Deploy path to set for Deployer action.
  public-url:
    description: The URL under that the deployment will be reachable.
  env-vars:
    description: Environment variables to set on the host (json encoded).
  shall-sync:
    description:
      This is a newly created environment that shall by synced from the parent
      environment.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'git-pull-request'
  color: 'purple'
