name: Sync Hosting.de
description: Helpful action to build push-to-deploy actions with Hosting.de
author: Richard Henkenjohann

inputs:
  auth-token:
    description: The API authentication token, from the Hosting.de admin panel.
    required: true
  from:
    description: The environment to use its data from. Defaults to the parent environment.
  to:
    description: The environment that gets overridden. Must not be the parent environment.
    required: true
  app:
    description: Limit sync to one app.
    default: ''
  files:
    description: You can disable sync of files.
    default: 'true'
  databases:
    description: You can disable sync of databases.
    default: 'true'
  only-databases:
    description: You can limit sync of databases to given.
    default: ''
  project-prefix:
    description:
      A prefix used to identify resources on Hosting.de. Must be kept unique under all projects under the account. Keep
      it short, e.g. `project1`.
    required: true
  ssh-private-key:
    description: The SSH private key to access webspaces.
    required: true

runs:
  using: node20
  main: dist/index.js
