name: Setup Hosting.de
description: Helpful action to build push-to-deploy actions with Hosting.de
author: Richard Henkenjohann

inputs:
  auth-token:
    description: The API authentication token, from the Hosting.de admin panel.
    required: true
  app:
    description:
      You can only deploy one app on a time, provide the key of the current application defined in the config file.
    default: app
  project-prefix:
    description:
      A prefix used to identify resources on Hosting.de. Must be kept unique under all projects under the account. Keep
      it short, e.g. `project1`
    default: ''
    required: true
  ssh-public-key:
    description: The SSH public key that matches the private key configured for deploying.
    required: true

outputs:
  ssh-user:
    description: Username for ssh connect.
  ssh-host:
    description: Hostname for ssh connect
  ssh-port:
    description: Port for ssh connect.
  http-user:
    description: User that runs the php process (for Deployer writable action).
  deploy-path:
    description: Deploy path to set for Deployer action.
  public-url:
    description: The URL under that the deployment will be reachable.
  env-vars:
    description: Environment variables to set on the host (json encoded).
  php-version:
    description: PHP version used for runtime.
  php-extensions:
    description: PHP extensions available in runtime.
  sync-files:
    description:
      This is true when this is a newly created webspace that files shall be synced from the parent environment.
  sync-databases:
    description:
      A whitespace separated list of databases that are newly created and shall be synced from the parent environment.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'git-pull-request'
  color: 'purple'
